/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-06-02 21:19:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Laptop;
import java.util.List;
import model.Laptop;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Laptop");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ru\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Автомобили</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1 class=\"mb-4\">Характеристики ноутбуков</h1>\r\n");
      out.write("    <table class=\"table table-striped\">\r\n");
      out.write("        <thead class=\"thead-dark\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th scope=\"col\">Модель</th>\r\n");
      out.write("            <th scope=\"col\">Процессор</th>\r\n");
      out.write("            <th scope=\"col\">Оперативная память</th>\r\n");
      out.write("            <th scope=\"col\">Накопитель</th>\r\n");
      out.write("            <th scope=\"col\">Экран</th>\r\n");
      out.write("            <th scope=\"col\">Цена, $</th>\r\n");
      out.write("            <th scope=\"col\"></th>\r\n");
      out.write("            <th scope=\"col\"></th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        ");
 List<Laptop> laptopsList = (List<Laptop>) request.getAttribute("laptopsList");
            for (Laptop laptop : laptopsList) { 
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print( laptop.getModel() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( laptop.getProcessor() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( laptop.getRAM() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( laptop.getStorage_drive() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( laptop.getDisplay() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( laptop.getPrice() );
      out.write("</td>\r\n");
      out.write("            <td><a href=\"edit?laptopsID=");
      out.print( laptop.getId() );
      out.write("\" class=\"btn btn-primary\"><i class=\"fas fa-pencil-alt\"></i></a></td>\r\n");
      out.write("            <td><a href=\"delete?laptopsID=");
      out.print( laptop.getId() );
      out.write("\" class=\"btn btn-outline-danger\"><i class=\"fas fa-trash-alt\"></i></a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <hr style=\"margin-top: 60px;\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\" style=\"margin-top: 60px; margin-bottom: 100px;\">\r\n");
      out.write("        <h2>Добавить ноутбук</h2>\r\n");
      out.write("        <form action=\"addition\" method=\"post\" id=\"addition\">\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group col-md-6\">\r\n");
      out.write("                    <label for=\"model\">Модель:</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"model\" name=\"model\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-6\">\r\n");
      out.write("                    <label for=\"processor\">Процессор:</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"processor\" name=\"processor\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-6\">\r\n");
      out.write("                    <label for=\"RAM\">Оперативная память (GB):</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"RAM\" name=\"RAM\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-6\">\r\n");
      out.write("                    <label for=\"storage_drive\">Накопитель (GB):</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"storage_drive\" name=\"storage_drive\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-6\">\r\n");
      out.write("                    <label for=\"display\">Экран (дюймы):</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"display\" name=\"display\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-6\">\r\n");
      out.write("                    <label for=\"price\">Цена ($):</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"price\" name=\"price\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\" id=\"add\">Добавить</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
